### ISSUE TITLE
What does it do and how does it work

### ISSUE THREAD

**Issue by ahmetozalp** [AlcaDesign/Twitch-SiteOptions#2]
Hi if i did not get it wrong is this free bit?

**Comment by AlcaDesign** [comment]
I'm not sure what you're saying in the description, but based on the title:

# What it is:

This repository is purposed with recording changes in [Twitch's "site_options.js" file located here.](https://www.twitch.tv/site_options.js) You can see the changes [here.](https://github.com/AlcaDesign/Twitch-SiteOptions/commits/master) I run the script every day and then look at the changes. I could set it up to run at a specific time every day, but I like to do it myself :)

# How it works:

If you look at [the bottom of the `update.js` file,](https://github.com/AlcaDesign/Twitch-SiteOptions/blob/master/update.js) you will see a pretty much plain English version of what it does. It gets the data, removes the excess Javascript so that it can be JSON, parse it as JSON, save it to a variable for better use, check against the old data, save the new data to file, update it on Github.
